apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-price-demo-app
spec:
  template:
    spec:
      containers:
      - name: loan-price-demo-app
        env:
        - name: ENVIRONMENT
          value: e2e
