apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: shivaprasadreddy1/argocd-demo
  newTag: 819e9cd72d6bae13fb12caa62695d2a66c148ca4
resources:
- ../base
