apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
  - name: shivaprasadreddy1/argocd-demo
    newTag: 12345dummy

resources:
- ../base
