apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: shivaprasadreddy1/loan-price-demo-app
  newTag: 529d641d8f7736483eb57b24454a4ee4529f917a

resources:
- ../base
